### ISSUE TITLE
（追加要件）モーダル内コンテンツの高さが画面の高さより大きくても表示されるようにしてほしい。

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#10]
モーダル内コンテンツの高さが画面の高さより大きいと、コンテンツが画面外に出てしまい
表示されていないため、そこを対応していただけますか。

**Comment by YukaMurata** [comment]
画面の大きさよりもコンテンツの高さが大きくなっても表示される(コンテンツ下部が切れない)ようにcssで対応しました。
ご確認よろしくお願いいたします。
また、cssではなく、jsでの対応が必要だったのであれば、月曜に教えていただければと思います。
dab4c22

**Comment by liberta793** [comment]
期間が空いてしまい、すみません。
対応ありがとうございます。
現状でも問題ありませんが、モーダルは上下中央に表示されるように修正していただけますか。
`overflow-y: scroll; `はそのままで問題ありません。

**Comment by YukaMurata** [comment]
遅くなってしまい、申し訳ございません。
こちら、対応いたしましたので、確認よろしくお願いいたします。
4899230

**Comment by liberta793** [comment]
確認できました!
