### ISSUE TITLE
（追加要件）各リンクに応じたモーダル内コンテンツが表示されるようにしてほしい。

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#11]
現状、リンクとモーダル内コンテンツは1つですが、
リンクとモーダル内コンテンツを3つ用意して、
各リンクに応じたモーダル内コンテンツが表示されるようにしていただけますか。

1のリンクをクリックしたら1のコンテンツが表示され、
2のリンクをクリックしたら2のコンテンツが表示されるようにしてください。

**Comment by YukaMurata** [comment]
遅くなって申し訳ございません。
e0d64f3
上記、対応いたしました。
お手隙の際に確認よろしくお願いいたします。

**Comment by liberta793** [comment]
確認できました!
