### ISSUE TITLE
コミットメッセージがわかりづらい

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#12]
コミットメッセージの「commit」は何をしたのかわからないため、適切なものに修正してください。
間違えてコミットした後でも修正はできるため、以下を参考にしてください。

- [git commit --amendでコミットメッセージを修正](http://qiita.com/piruty_joy/items/2fbfd26fd8dcbfed592a)
- [【備忘録】過去のコミットメッセージを変更する](http://nnsnodnb.hatenablog.jp/entry/how-to-git-rebase)

歴史を変更する場合、変更後にforce pushをする必要がありますが、
個人のリポジトリなので問題ありません。（業務リポジトリでは基本的にしないでください）

むしろ個人のリポジトリなので、ガンガン試してみると良いと思います。
以下目を通しておくと良いかもです。

- [Gitでやらかした時に使える19個の奥義](http://qiita.com/muran001/items/dea2bbbaea1260098051)
- [Gitでやらかさないための事前予防策](http://qiita.com/muran001/items/f13742b51da3a22117ee)
- [Git 作業における commit と push の頻度について](http://qiita.com/kozyty@github/items/87fa95a236b6142f7c10)

**Comment by YukaMurata** [comment]
すみません、以後気をつけます。
