### ISSUE TITLE
Github Pagesに関して

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#14]
念のためお伝えしておきます。

現在、このリポジトリを修正する度に
https://github.com/YukaMurata/YukaMurata.github.io
にもコミットしてページを確認できるようにしているみたいですが、
gh-pagesブランチを制作するか、docsディレクトリにファイルを格納すれば
このリポジトリを更新しただけでもページ公開はできます。

- [GitHubでWebページを公開する方法](http://qiita.com/Yuki_Yamashina/items/5d8208c450195b65344c)
- [gh-pagesをサブディレクトリ内で管理](http://qiita.com/tyfkda/items/1ee5e50a39729a301520)

上記を知っていたうえで複数リポジトリにコミットしているなら構いませんか、
面倒臭いと感じているなら上記の対応をしてください。

**Comment by YukaMurata** [comment]
作業しているディレクトリで管理できるようになりました。

**Comment by liberta793** [comment]
確認できました!
