### ISSUE TITLE
単位vhに関して

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#15]
念のため、単位vhに関してお伝えしておきます。

高さにvhを利用していますが、一部ブラウザでは使えないため、
業務の際はサポートをするブラウザを確認してから利用した方が良いです。
http://caniuse.com/#feat=viewport-units

今回はvhでも問題ありません。
このissueを一読したらcloseして構いません。

**Comment by YukaMurata** [comment]
ありがとうございます。
使っている箇所は%に変更いたします。

**Comment by liberta793** [comment]
了解ですー。
引き続きよろしくお願いいたします!
