### ISSUE TITLE
フェードインのちらつきに関して

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#16]
こちらに修正方法のコメントを記述しましたので、ご確認ください。

https://github.com/YukaMurata/modal/commit/711caaeb9bdfb0a0118bed22befbf4a4dfcb9032#commitcomment-20624729

**Comment by YukaMurata** [comment]
ありがとうございます。
.modalにz-indexを付け加えました。現在fadeIn等のjsの修正をしておりますのでそちらを対応次第こちらも一緒に見ていただけると助かります。

**Comment by liberta793** [comment]
> 現在fadeIn等のjsの修正をしておりますのでそちらを対応次第こちらも一緒に見ていただけると助かります。

こちらは対応済みでしょうか。

**Comment by YukaMurata** [comment]
すみません、そうです。
fadeIn等の修正をいたしました。
ご確認よろしくお願いいたします。

**Comment by liberta793** [comment]
ありがとうございます。確認しますね。
ちらつきは直っているためこの課題は閉じます。
