### ISSUE TITLE
HTMLのスペースにばらつきがある。余計なスペースが存在する。

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#17]
HTMLのスペースにばらつきがある。余計なスペースが存在するため修正していただけますか。
書き方の問題なので現状でも実装したものは動きますが、以下の理由で修正してほしいです。

- 見づらいため。
- 書いた人以外がコードを理解するのに時間がかかるため。
- ツールを使えば自動でコードを整形してくれるため、一度設定さえすれば今後何かする必要はないため。

手動で修正する必要はないです。WebStormだったら自動でコードを整形してくれるはずなので、確認してみてください。

もちろん、以下のようにWebStorm以外のエディタでもコードを自動整形している拡張はありますので、自分の利用しているエディタにそのような拡張がないか確認してみてください。（sublimeは自動で整形してくれる拡張はないかもです）
[HTML Programming in VS Code](https://code.visualstudio.com/Docs/languages/html)

**Comment by YukaMurata** [comment]
ありがとうございます。
こちら、修正いたしました。
確認よろしくお願いいたします。

**Comment by liberta793** [comment]
確認できました!
今後、何かを修正した際は以下のように修正したコミットのURLを貼っていただけると助かります。
https://github.com/YukaMurata/modal/commit/6d50d7efd7c7c96d5cb0b0f48ce7139e97f43339

お手数ですが、よろしくお願いいたします。

**Comment by YukaMurata** [comment]
申し訳ございません。
承知しました。

**Comment by liberta793** [comment]
いえー、こちらの説明不足ですので気になさらず。
