### ISSUE TITLE
.gitigonoreの追加

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#18]
.ideaや.DS_Storeを追加してしまった後に消しているようなので、
リポジトリのルートに.gitigonoreファイルを追加してみてください。

.gitigonoreに指定のファイルやディレクトリを記述すると、
それらをGitは無視するため、不要なファイルを間違えてコミットすることもなくなります。

以下のように無視したいファイルやディレクトリを記述してください。
https://github.com/starterkits/frontend-starterkit-webpack/blob/master/.gitignore

**Comment by YukaMurata** [comment]
ファイルを追加しました。
ご確認よろしくお願いいたします。

**Comment by liberta793** [comment]
確認できました!
