### ISSUE TITLE
package.jsonの追加

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#19]
`package.json`を追加し、適切な記述をしておけば他の作業者は`npm install`を実行するだけで必要なパッケージをインストールしてすぐにgulpなどを実行できます。

そのため、`package.json`を追加していただけますか。
今回は以下のコマンドで追加できるはずです。

`npm init`

`npm install gulp-sass gulp-pleeease --save-dev`

**Comment by YukaMurata** [comment]
ありがとうございます。
ファイルを作成いたしました。
b4a8be5

**Comment by liberta793** [comment]
確認できました!
`package.json`の項目などに関しては以下を見ると良いと思います。

- [npm package.json 取扱説明書](http://liberty-technology.biz/PublicItems/npm/package.json.html)
- [npmとpackage.json使い方](http://kokudori.hatenablog.com/entry/2013/04/04/025521)
