### ISSUE TITLE
（追加要件）ESLintを利用してほしい。

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#2]
「気になる点」で指摘した、スペースとタブの混同空行や末尾の不要なスペースなどに関してはESLintという構文解析ツールがあるのでそれを利用してください。

- [ESLint](http://eslint.org/)
- [ESLint 最初の一歩](http://qiita.com/mysticatea/items/f523dab04a25f617c87d)
- [共有設定でらくらく ESLint](http://qiita.com/mysticatea/items/dc35ced6bd5e782f50cd)

ESLintを利用する理由ですが、以下になります。

- 正しい構文を書くため
- チェックツールを利用せずに人間の手だけで100%正しい構文を書くのは不可能なため
- チーム開発だったら構文を統一できるため
- 構文正しくなくても動くていえば動くが、そんなにコストがかからず正しい構文を書けるなら使う越したことはないから

利用方法ですが、gulpや、コマンド、WebStormで実行したり手段は問いません。
ESLintを利用できるようにったら、このissueは閉じます。

**Comment by YukaMurata** [comment]
コマンドでファイルを指定して実行できるようになりました。
ただ、.eslintrcのenvにはほとんど追記していない状況です。

**Comment by liberta793** [comment]
ありがとうございます。
.eslintrcを確認したいため、プッシュしていただけますか。

**Comment by YukaMurata** [comment]
プッシュしました。
ご確認よろしくお願いいたします。

**Comment by liberta793** [comment]
ありがとうございます。
env箇所の入れ子のスペースが気になりました。

```
"env": {"browser": true,
"jquery": true},
```

理由や意図があるならそのままで問題ありませんが、
特になければ以下に修正していただけますか。

```
{
	"extends": ["eslint:recommended"],
	"plugins": [],
	"parserOptions": {},
	"env": {
		"browser": true,
		"jquery": true
	},
	"globals": {},
	"rules": {}
}
```

細かくて恐縮ですが、よろしくお願いいたします。

**Comment by YukaMurata** [comment]
特に意味はありません。
上記に修正いたしました。
ご指摘ありがとうございます！

**Comment by YukaMurata** [comment]
ありがとうございます。
上記修正いたしました。
18e40b6

**Comment by YukaMurata** [comment]
ありがとうございます。
上記対応しましたので、ご確認よろしくお願いいたします。
1f6b4c8

**Comment by liberta793** [comment]
確認できました!
