### ISSUE TITLE
ボタンにcusor: pointerを追加する

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#20]
現状のボタンだとホバーしても矢印のアイコンのままで、ユーザーが押せるかどうかの判断ができないため、該当に要素にcsscusor: pointerを追加してください。

**Comment by YukaMurata** [comment]
対応いたしましたので、ご確認よろしくお願いいたします。
9c9a386

**Comment by liberta793** [comment]
閉じるボタンは確認できました。

button modal_1
button modal_2
button modal_3

にもcusor: pointerを追加していただけますか。

**Comment by YukaMurata** [comment]
すみません。
対応いたしました。
1b7cd11
確認よろしくお願いいたします。

**Comment by liberta793** [comment]
確認できました!
