### ISSUE TITLE
モーダル内のコンテンツをクリックするとモーダルが閉じてしまう

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#21]
モーダル内のコンテンツをクリックするとモーダルが閉じてしまいます。
閉じるボタンとオーバーレイをクリックした時だけ閉じるようにしてください。

**Comment by YukaMurata** [comment]
お疲れ様です。
overlayにのみfadeOutの処理を与えると、z-indexの関係か、処理が走りません。週明けにでも教えていただければと思います。よろしくお願いいたします。

**Comment by liberta793** [comment]
>z-indexの関係か、処理が走りません。

modalクラスoverlayクラスより、手前にきているようなのでmodalクラスにクリック時の処理を追加してください。

しかし、普通にmodalクラスに処理を追加すると、モーダル内のコンテンツをクリックしてもモーダルが閉じてしまうため、以下のようにmodal_contentクラスをクリック時の処理に`e.stopPropagation`を利用してください。

```js
$('.modal_content').click(function (e) {
    e.stopPropagation();
});
```

`e.stopPropagation`は親要素のイベントの伝播を防ぐメソッドです。
通常の場合はmodal_contentクラスをクリックすると、その親要素であるmodalクラスにもクリックイベントが伝播していまい、モーダルを閉じる処理が実行されてしまいます。

しかし、`e.stopPropagation`を利用すれば、modal_contentクラスをクリックしてもmodalクラスにはクリックイベントが伝播しないです。そのため閉じる処理は実行されないです。

上記説明がわかりづらい場合、聞いてください。

**Comment by YukaMurata** [comment]
ありがとうございます。
上記、対応いたしました。
c0ab916
ご確認よろしくお願いいたします。

**Comment by liberta793** [comment]
確認できました!
