### ISSUE TITLE
velocity.jsを利用する

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#22]
velocity.jsを読み込んでいるため、velocity.jsを使ってフェードイン、フェードアウト処理を実装してください。

**Comment by liberta793** [comment]
期間が空いてしまい、すみません。
こちら、対応済みでしょうか。

**Comment by YukaMurata** [comment]
すみません、jsにすでに使用しております。
確認よろしくお願いいたします。

**Comment by liberta793** [comment]
確認できました。
