### ISSUE TITLE
（追加要件）モーダルが画面全体に表示されていないため、reset.cssをあててほしい。

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#4]
モーダルが画面全体に表示されていないため、reset.cssをあててください。（reset.cssの種類は色々ありますが、どれをあてても構いません。実案件でreset.cssを使わないことはないため、今後の課題でも必ずあててください）

**Comment by YukaMurata** [comment]
reset.cssをあてました。
最小限のものを、普段使っているものから持ってきています。

**Comment by liberta793** [comment]
このリポジトリだと確認できましたが
https://yukamurata.github.io/modal/modal.html
には反映されていないようです。

複数のリポジトリにpushするのは面倒臭いと思うため、
先に以下のissueを対応した方が良いかもです。
https://github.com/YukaMurata/modal/issues/14

**Comment by liberta793** [comment]
確認できました!
