### ISSUE TITLE
PC・SP対応前提だが、SPの文字が小さく見える。

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#5]
PC・SP対応前提のはずですが、SPの文字が小さく見えるためviewportを指定してださい。

**Comment by YukaMurata** [comment]
viewport指定しました。
https://yukamurata.github.io/modal/modal.html

**Comment by YukaMurata** [comment]
viewport指定しました。
ご確認よろしくお願いいたします。
https://yukamurata.github.io/modal/modal.html

**Comment by liberta793** [comment]
確認できました。

user-scalableは状況によって使い分ける可能性があるため、以下に目を通しておいてください。
[user-scalable=noを使う理由と弊害（スマホのviewportを見直す）](http://2ndidea.com/accessibility/pros-cons-of-user-scalable-no/#post6-section2-1)

今回はuser-scalable=noでも問題ありませんでこのissueは閉じます。
