### ISSUE TITLE
どこがモーダルのオーバーレイで、どこがコンテンツかわからない。

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#6]
どこがモーダルのオーバーレイで、どこがコンテンツかわからないため以下のように違いがわかるように修正をしてください。
![modal](https://cloud.githubusercontent.com/assets/13026287/22230518/6ed089fa-e221-11e6-867f-a7f143ba33a2.jpg)

**Comment by YukaMurata** [comment]
オーバーレイとコンテンツを分けました。
※現在別の作業中にてこのコンテンツの動作が鈍いです。

**Comment by liberta793** [comment]
確認できました!
