### ISSUE TITLE
bodyにposition: relativeは影響範囲が広すぎて危ない。

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#7]
bodyに`position: relative`は影響範囲が広すぎて危ないため、モーダル用の要素に`position: relative`を指定してください。

**Comment by YukaMurata** [comment]
bodyにposition:rerativeをやめ、モーダル用のinnerを用意し、position:rerativeを指定しました。

**Comment by liberta793** [comment]
inner確認できました。
しかし、こちらも https://github.com/YukaMurata/modal/issues/4 と同様で反映漏れがあるみたいです。
https://github.com/YukaMurata/modal/issues/14 を先に確認した方が良いかもです。

**Comment by liberta793** [comment]
確認できました!
