### ISSUE TITLE
（追加要件）cssはgulpファイルを制作してscssからコンパイルしてほしい。

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#8]
cssはgulpファイルを制作してscssからコンパイルしてください。

**Comment by YukaMurata** [comment]
scssからコンパイルできるようにgulpファイルを制作しました。
ご確認よろしくお願いいたします。
5ebbbcc

**Comment by liberta793** [comment]
確認できました!
package.jsonも追加してほしいため別issueを立てます。

**Comment by liberta793** [comment]
package.jsonを追加してほしいissueです。
https://github.com/YukaMurata/modal/issues/19
