### ISSUE TITLE
アニメーション中にクリック時の処理が実行されている。

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/modal#9]
アニメーション中にクリック時処理が実行されており、予期せぬ動作を招く可能性があります。
そのためアニメーション中はクリック時の処理が実行されないようにしてください。

**Comment by YukaMurata** [comment]
遅くなって申し訳ございません。
e0d64f3
上記、対応いたしました。
お手隙の際に確認よろしくお願いいたします。

**Comment by liberta793** [comment]
この実装の考え方

- アニメーション中かどうかを判定する変数を作る
- クリック時にアニメーション中だったら処理は実行しない、アニメーション中でなければ処理を実行する
- アニメーション終了時、アニメーション中かどうかの変数を更新する

みたいな感じでお願いします。

**Comment by YukaMurata** [comment]
お疲れ様です。
上記、対応しました。
ご確認よろしくお願いいたします。

**Comment by liberta793** [comment]
私も知らなかったですがaddを利用すると、fadeOutの中の処理がすぐに実行されてしまうみたいです。
そのため、セレクタ毎にフェードアウト処理を記述してください。
`$('.modal[data-modal="'+ modaldata + '"], .overlay')`のように複数のセレクタを一括で指定するのもありですが、セレクタ毎に処理を分ける必要になることを考慮して、あらかじめ分けといた方が良いかもしれないです。

あと、bindEventとaddEventを分ける理由はないと思うので、どちらか一つにまとめてください。

**Comment by liberta793** [comment]
あと、bindEventとaddEventを分ける理由はないと思うので、どちらか一つにまとめてください。

**Comment by YukaMurata** [comment]
承知しました。
対応いたします。

**Comment by YukaMurata** [comment]
お疲れ様です。
セレクタごとに分けてfadeさせました。
ご確認よろしくお願いいたします。
c7285c6
9c9a386

**Comment by liberta793** [comment]
確認できました!
